apiVersion: v1
kind: Service
metadata:
  name: wse-rtmp
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 1935
      targetPort: rtmp
      protocol: TCP
      name: rtmp
  selector:
    app: wse
---
apiVersion: v1
kind: Service
metadata:
  name: wse-admin
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8086
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    app: wse