apiVersion: v1
kind: Service
metadata:
  name: {{.Values.MYSQL_APP_NAME}}
  labels:
    app: {{.Values.APP_NAME}}
spec:
  ports:
    - port: {{.Values.MYSQL_PORT}}
  selector:
    app: {{.Values.APP_NAME}}
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: {{.Values.MYSQL_APP_NAME}}
  labels:
    app: {{.Values.APP_NAME}}
spec:
  replicas: {{.Values.REPLICAS}}
  storageClassName: {{.Values.STORAGE_CLASS_NAME}}
  selector:
    matchLabels:
      app: {{.Values.APP_NAME}}
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{.Values.APP_NAME}}
        tier: mysql
    spec:
#START# For scheduling pods on master node
#      tolerations:
#        - key: "node-role.kubernetes.io/master"
#          effect: "NoSchedule"
#          operator: "Exists"
#END#
      containers:
      - image: {{.Values.MYSQL_IMAGE}}
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: {{.Values.MYSQL_PORT}}
          name: mysql
        volumeMounts:
        - name: {{.Values.MYSQL_VOLUME_MOUNT}}
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: {{.Values.MYSQL_VOLUME_MOUNT}}
      labels:
        app: {{.Values.APP_NAME}}
    spec:
      storageClassName: {{.Values.STORAGE_CLASS_NAME}}
      accessModes: [ "{{.Values.ACCESS_MODE}}" ]
      resources:
        requests:
          storage: {{.Values.MYSQL_STORAGE}}

