apiVersion: v1
kind: Service
metadata:
  name: {{.Values.APP_NAME}}
  labels:
    app: {{.Values.APP_NAME}}
#  annotations:
#    kube-router.io/service.dsr: tunnel
spec:
  ports:
    - port: {{.Values.WORDPRESS_PORT}}
  selector:
    app: {{.Values.APP_NAME}}
    tier: frontend
  externalIPs:
    - {{.Values.EXTERNAL_IP}}
  type: ClusterIP  
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: {{.Values.APP_NAME}}
  labels:
    app: {{.Values.APP_NAME}}
spec:
  replicas: {{.Values.REPLICAS}}
  selector:
    matchLabels:
      app: {{.Values.APP_NAME}}
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{.Values.APP_NAME}}
        tier: frontend
    spec:
#START# For scheduling pods on master node
#      tolerations:
#        - key: "node-role.kubernetes.io/master"
#          effect: "NoSchedule"
#          operator: "Exists"
#END# 
      containers:
      - image: {{.Values.WORDPRESS_IMAGE}}
        name: {{.Values.APP_NAME}}
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: {{.Values.WORDPRESS_CONTAINER_PORT}}
          name: {{.Values.APP_NAME}}
        volumeMounts:
        - name: {{.Values.WORDPRESS_VOLUME_MOUNT}}
          mountPath: /var/www/html
  volumeClaimTemplates:
  - metadata:
      name: {{.Values.WORDPRESS_VOLUME_MOUNT}}
      labels:
        app: {{.Values.APP_NAME}}
    spec:
      storageClassName: {{.Values.STORAGE_CLASS_NAME}}
      accessModes: [ "{{.Values.ACCESS_MODE}}" ]
      resources:
        requests:
          storage: {{.Values.WORDPRESS_STORAGE}}
