apiVersion: v1
kind: Service
metadata:
  name: {{.Values.APP_NAME}}
  labels:
    app: {{.Values.APP_NAME}}
spec:
  ports:
    - port: {{.Values.WORDPRESS_PORT}}
  selector:
    app: {{.Values.APP_NAME}}
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.WORDPRESS_PV_CLAIM}}
  labels:
    app: {{.Values.APP_NAME}}
spec:
  storageClassName: {{.Values.STORAGE_CLASS_NAME}}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.WORDPRESS_STORAGE}}
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{.Values.APP_NAME}}
  labels:
    app: {{.Values.APP_NAME}}
spec:
  selector:
    matchLabels:
      app: {{.Values.APP_NAME}}
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{.Values.APP_NAME}}
        tier: frontend
    spec:
      containers:
      - image: {{.Values.WORDPRESS_IMAGE}}
        name: {{.Values.APP_NAME}}
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: {{.Values.WORDPRESS_CONTAINER_PORT}}
          name: {{.Values.APP_NAME}}
        volumeMounts:
        - name: {{.Values.WORDPRESS_VOLUME_MOUNT}}
          mountPath: /var/www/html
      volumes:
      - name: {{.Values.WORDPRESS_VOLUME_MOUNT}}
        persistentVolumeClaim:
          claimName: {{.Values.WORDPRESS_PV_CLAIM}}
