apiVersion: v1
kind: ConfigMap
metadata:
  name: varnish-cfg
  namespace: default
data:
  default.vcl: |
    vcl 4.0;
    backend default {
        .host = "origin";
        .port = "8080";
    }
    sub vcl_recv {}
    sub vcl_deliver {
        if (obj.hits > 0) {
           set resp.http.X-Cache = "Platina-HIT";
        } else {
           set resp.http.X-Cache = "Platina-MISS";
        }
    }
  secret: |
    1234123412341234
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: varnish
  labels:
    app: varnish
spec:
  replicas: 1
  selector:
    matchLabels:
      app: varnish
  template:
    metadata:
      labels:
        app: varnish
    spec:
      volumes:
      - name: config-vol
        configMap:
          name: varnish-cfg
      containers:
      - name: varnish
        image: zoharm/varnish-exp-test
        env:
        - name: CACHE_SIZE
          value: 500m
        - name: VARNISHD_PARAMS
          value: "-p default_ttl=86400 -p default_grace=3600" 
        volumeMounts:
        - name: config-vol
          mountPath: /etc/varnish
        ports:
        - containerPort: 80
        - name: varnish-metrics
          containerPort: 9131
        securityContext:
          privileged: true
      - name: nginx
        image: stigt/nginx-alpine
        ports:
        - containerPort: 443
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
---
apiVersion: v1
kind: Service
metadata:
  annotations:
#    kube-router.io/service.dsr: tunnel
  name: varnish
  labels:
    app: varnish
spec:
  selector:
    app: varnish
  externalIPs:
  - 2.2.2.2
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  - name: varnish-metrics
    protocol: TCP
    port: 9131
    targetPort: 9131
